const RANKS=[
["E-1","Private","Pvt","Enlisted"],["E-2","Private First Class","PFC","Enlisted"],["E-3","Lance Corporal","LCpl","Enlisted"],["E-4","Corporal","Cpl","Enlisted"],["E-5","Sergeant","Sgt","Enlisted"],["E-6","Staff Sergeant","SSgt","Enlisted"],["E-7","Gunnery Sergeant","GySgt","Enlisted"],["E-8","Master Sergeant","MSgt","Enlisted"],["E-8","First Sergeant","1stSgt","Enlisted"],["E-9","Master Gunnery Sergeant","MGySgt","Enlisted"],["E-9","Sergeant Major","SgtMaj","Enlisted"],["E-9","Sergeant Major of the Marine Corps","SMMC","Enlisted"],["E-10","Senior Enlisted Advisor / Custom Roblox Rank","SEA","Enlisted"],["O-1","Second Lieutenant","2ndLt","Officer"],["O-2","First Lieutenant","1stLt","Officer"],["O-3","Captain","Capt","Officer"],["O-4","Major","Maj","Officer"],["O-5","Lieutenant Colonel","LtCol","Officer"],["O-6","Colonel","Col","Officer"],["O-7","Brigadier General","BGen","Headquarters"],["O-8","Major General","MajGen","Headquarters"],["O-9","Lieutenant General","LtGen","Headquarters"],["O-10","General","Gen","Headquarters"],["HQ","Master General","Gen","HQ Leadership"],["HQ","Inspector Staff","IS","HQ Leadership"],["HQ","Inspector General","IG","HQ Leadership"],["HQ","Chief of Staff","CoS","HQ Leadership"],["HQ","Deputy Commandant of the Marine Corps","DCMC","HQ Leadership"],["HQ","Assistant Commandant of the Marine Corps","ACMC","HQ Leadership"],["HQ","Commandant of the Marine Corps","CMC","HQ Leadership"]];
const cfg=window.USMC_CONFIG;let state={personnel:[],access:{role:"guest"}};let selectedId=null;let now=Date.now();let latestCode="";let pendingRankChange=null;let pendingWarning=null;let loadingState=false;
const $=id=>document.getElementById(id);const sessionKey="usmc_hq_session";
function esc(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
function toast(message){$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),3500)}
async function api(action,data={}){const token=localStorage.getItem(sessionKey);const res=await fetch(`${cfg.supabaseUrl}/functions/v1/${cfg.functionName}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":cfg.publishableKey,...(token?{"x-hq-session":token}:{})},body:JSON.stringify({action,...data})});const out=await res.json().catch(()=>({error:"Invalid server response."}));if(!res.ok)throw new Error(out.error||"Request failed.");return out}
function current(){return state.personnel.find(x=>x.id===selectedId)||state.personnel[0]||null}
function elapsed(p){if(!p)return 0;return Number(p.elapsed_seconds)+(p.is_running?Math.max(0,Math.floor((now-new Date(p.started_at).getTime())/1000)):0)}
function pad(v,n=2){return String(v).padStart(n,"0")}
async function load(){if(loadingState)return;loadingState=true;try{state=await api("state");if(!state.personnel.some(x=>x.id===selectedId))selectedId=state.personnel[0]?.id||null;render()}catch(e){toast(e.message)}finally{loadingState=false}}
function render(){const p=current(),role=state.access.role;$("access-name").textContent=role==="guest"?"Guest Access":state.access.name;$("access-rank").textContent=role==="guest"?"View only":`${state.access.rank_code} · ${state.access.rank_name}`;$("role-badge").textContent=role==="guest"?"Guest · View only":`${role==="owner"?"Owner HQ":"HQ Leadership"} · ${state.access.rank_name}`;$("selected-name").textContent=p?.name||"No personnel selected";$("selected-rank").textContent=p?`${RANKS[p.rank_index][0]} · ${RANKS[p.rank_index][1]}`:"—";document.querySelectorAll(".authority").forEach(x=>x.classList.toggle("hidden",role==="guest"));document.querySelectorAll(".owner-only").forEach(x=>x.classList.toggle("hidden",role!=="owner"));$("roster").innerHTML=state.personnel.length?state.personnel.map(x=>`<div class="row ${x.id===p?.id?"selected":""}" data-id="${x.id}"><div><strong>${esc(x.name)}</strong><small>${esc(RANKS[x.rank_index][1])}</small></div><span class="rank">${RANKS[x.rank_index][0]}</span>${role==="owner"?`<button class="remove" data-remove="${x.id}" type="button">Remove</button>`:""}</div>`).join(""):`<div class="empty">No personnel yet.</div>`;document.querySelectorAll("[data-id]").forEach(x=>x.onclick=()=>{selectedId=x.dataset.id;render()});document.querySelectorAll("[data-remove]").forEach(x=>x.onclick=e=>{e.stopPropagation();removePerson(x.dataset.remove)});const rank=p?RANKS[p.rank_index]:null;$("code-status").textContent=!p?"Select an HQ-titled person.":p.rank_index<23?"This person is not in an HQ-titled rank.":p.has_access_code?"An active personal HQ code exists.":"No active HQ code exists.";$("create-code").disabled=!p||p.rank_index<23;$("revoke-code").disabled=!p||!p.has_access_code;renderClock()}
const renderPanel=render;render=function(){renderPanel();const role=state.access.role;$("logs-link").classList.toggle("hidden",role==="guest");$("warning-link").classList.toggle("hidden",role==="guest");const p=current(),saved=role==="owner"?p?.saved_code:null;latestCode=saved||"";if(saved){$("code-person").textContent=p.name;$("generated-code").textContent=saved;$("code-result").classList.remove("hidden")}else $("code-result").classList.add("hidden");document.querySelectorAll("#roster [data-id]").forEach(row=>{const person=state.personnel.find(x=>x.id===row.dataset.id),detail=row.querySelector("small");if(person&&detail)detail.textContent=`${RANKS[person.rank_index][1]} · ${person.warning_count||0} warning${person.warning_count===1?"":"s"}`});const alerts=role==="owner"?state.personnel.filter(x=>(x.warning_count||0)>=3):[];$("warning-alerts").innerHTML=alerts.map(x=>`<a href="warning.html?personnel=${encodeURIComponent(x.id)}"><strong>${esc(x.name)} Has reached 3 warnings.</strong><b>Click Here To See</b></a>`).join("");$("warning-alerts").classList.toggle("hidden",!alerts.length)};
function renderClock(){const t=elapsed(current());$("days").textContent=pad(Math.floor(t/86400),3);$("hours").textContent=pad(Math.floor(t%86400/3600));$("mins").textContent=pad(Math.floor(t%3600/60));$("secs").textContent=pad(t%60)}
function showApp(){ $("entry").classList.add("hidden");$("app").classList.remove("hidden");load() }
$("choose-hq").onclick=()=>{$("entry-options").classList.add("hidden");$("hq-form").classList.remove("hidden");$("entry-title").textContent="Sign in with HQ";$("entry-copy").textContent="Enter your personal HQ code. It identifies your HQ account and current leadership rank.";$("hq-code").focus()};
$("entry-back").onclick=()=>{$("entry-options").classList.remove("hidden");$("hq-form").classList.add("hidden");$("entry-title").textContent="Choose how to enter"};
$("choose-guest").onclick=()=>{localStorage.removeItem(sessionKey);state.access={role:"guest"};showApp()};
$("hq-form").onsubmit=async e=>{e.preventDefault();try{const out=await api("login",{code:$("hq-code").value.trim().toUpperCase()});localStorage.setItem(sessionKey,out.session);$("hq-code").value="";showApp();toast(`Signed in as ${out.access.name}.`)}catch(err){toast(err.message)}};
$("exit").onclick=async()=>{try{if(localStorage.getItem(sessionKey))await api("logout")}catch{}localStorage.removeItem(sessionKey);location.reload()};
$("add-form").onsubmit=async e=>{e.preventDefault();const names=$("new-name").value.split(",").map(x=>x.trim()).filter(Boolean);if(!names.length)return;try{state=await api("add",{names});$("new-name").value="";render();toast("Personnel added at E-1.")}catch(err){toast(err.message)}};
$("rank-form").onsubmit=e=>{e.preventDefault();const p=current(),command=$("rank-command").value.trim(),warningMatch=/^W([1-3])$/i.exec(command),removeMatch=/^R(1|2|3|ALL)$/i.exec(command.replace(/\s+/g,""));if(!p||!command)return;if(removeMatch){if(state.access.role!=="owner"){toast("Only the Owner can remove warnings.");return}const value=removeMatch[1].toUpperCase(),count=p.warning_count||0;if(!count){toast(`${p.name} has no warnings to remove.`);return}if(value!=="ALL"&&Number(value)>count){toast(`${p.name} only has ${count} warning${count===1?"":"s"}.`);return}const display=value==="ALL"?"R All":`R${value}`;pendingWarning={mode:"remove",id:p.id,name:p.name,command:display,level:value};$("warning-title").textContent=value==="ALL"?"Remove all warnings":`Remove warning ${value}`;$("warning-summary").textContent=`${p.name} · Command: ${display} · Current warnings: ${count}`;$("warning-reason-label").textContent="Removal reason";$("warning-reason").placeholder="Explain why this warning is being removed…";$("warning-reason").value="";$("warning-confirm").textContent=value==="ALL"?"Remove all warnings":`Remove warning ${value}`;$("warning-confirm").className="danger-button";$("warning-modal").classList.remove("hidden");document.body.classList.add("modal-open");$("warning-reason").focus();return}if(p.id===state.access.id){toast(warningMatch?"You cannot warn yourself.":"You cannot change your own rank.");return}if(state.access.role==="hq"&&p.rank_index>=state.access.rank_index){toast(warningMatch?"You cannot warn someone at your rank or higher.":"You cannot change someone at your rank or higher.");return}if(warningMatch){const level=Number(warningMatch[1]),next=(p.warning_count||0)+1;if(level!==next){toast(next>3?`${p.name} already has all three warnings.`:`The next warning for ${p.name} is W${next}.`);return}pendingWarning={mode:"issue",id:p.id,name:p.name,level};$("warning-title").textContent=`Issue warning ${level}`;$("warning-summary").textContent=`${p.name} · Command: W${level} · Current warnings: ${p.warning_count||0}`;$("warning-reason-label").textContent="Warning reason";$("warning-reason").placeholder="Explain why this warning is being issued…";$("warning-reason").value="";$("warning-confirm").textContent="Confirm warning";$("warning-confirm").className="warning-confirm";$("warning-modal").classList.remove("hidden");document.body.classList.add("modal-open");$("warning-reason").focus();return}pendingRankChange={id:p.id,name:p.name,command};$("reason-summary").textContent=`${p.name} · Command: ${command}`;$("rank-reason").value="";$("reason-modal").classList.remove("hidden");document.body.classList.add("modal-open");$("rank-reason").focus()};
function closeReasonModal(){pendingRankChange=null;$("reason-modal").classList.add("hidden");document.body.classList.remove("modal-open")}
$("cancel-reason").onclick=closeReasonModal;
$("reason-form").onsubmit=async e=>{e.preventDefault();if(!pendingRankChange)return;const reason=$("rank-reason").value.trim();if(reason.length<3){toast("Enter a reason with at least 3 characters.");return}const request={...pendingRankChange,reason};try{state=await api("rank",{id:request.id,command:request.command,reason});$("rank-command").value="";closeReasonModal();render();toast("Rank updated and logged.")}catch(err){toast(err.message)}};
function closeWarningModal(){pendingWarning=null;$("warning-modal").classList.add("hidden");document.body.classList.remove("modal-open")}
$("cancel-warning").onclick=closeWarningModal;
$("warning-form").onsubmit=async e=>{e.preventDefault();if(!pendingWarning)return;const reason=$("warning-reason").value.trim();if(reason.length<3){toast(`Enter a ${pendingWarning.mode==="remove"?"removal":"warning"} reason with at least 3 characters.`);return}const request={...pendingWarning,reason};try{if(request.mode==="remove"){state=await api("remove-warning-command",{id:request.id,command:request.command,reason});$("rank-command").value="";closeWarningModal();render();toast(request.level==="ALL"?`All warnings were removed from ${request.name}.`:`Warning ${request.level} was removed from ${request.name}.`)}else{state=await api("warn",{id:request.id,level:request.level,reason});$("rank-command").value="";closeWarningModal();render();toast(`${request.name} received Warning ${request.level}.`)}}catch(err){toast(err.message)}};
document.querySelectorAll("[data-timer]").forEach(b=>b.onclick=async()=>{const p=current();if(!p)return;try{state=await api("timer",{id:p.id,mode:b.dataset.timer,seconds:Number($("timer-seconds").value)||0});render();toast("Timer updated.")}catch(err){toast(err.message)}});
async function removePerson(id){const p=state.personnel.find(x=>x.id===id);if(!p||!confirm(`Remove ${p.name}?`))return;try{state=await api("remove",{id});render();toast("Personnel removed.")}catch(err){toast(err.message)}}
$("create-code").onclick=async()=>{const p=current();if(!p)return;try{const out=await api("create-code",{id:p.id});state=out.state;latestCode=out.code;$("code-person").textContent=out.name;$("generated-code").textContent=out.code;$("code-result").classList.remove("hidden");render();toast("New HQ code created.")}catch(err){toast(err.message)}};
$("copy-code").onclick=async()=>{if(!latestCode)return;try{await navigator.clipboard.writeText(latestCode);toast("HQ code copied.")}catch{toast("Select the code and copy it manually.")}};
$("revoke-code").onclick=async()=>{const p=current();if(!p||!confirm(`Revoke ${p.name}'s HQ code?`))return;try{state=await api("revoke-code",{id:p.id});latestCode="";$("code-result").classList.add("hidden");render();toast("HQ code revoked.")}catch(err){toast(err.message)}};
$("rank-list").innerHTML=RANKS.map((r,i)=>`<div class="rank-item"><b>${r[0]}</b><div><strong>${esc(r[1])}</strong><br><small>${esc(r[2])} · ${esc(r[3])}</small></div></div>`).join("");
setInterval(()=>{now=Date.now();renderClock()},1000);setInterval(()=>{if(!$("app").classList.contains("hidden"))load()},2000);
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&!$("app").classList.contains("hidden"))load()});window.addEventListener("focus",()=>{if(!$("app").classList.contains("hidden"))load()});
if(localStorage.getItem(sessionKey))showApp();
