const cfg=window.USMC_CONFIG;
const sessionKey="usmc_hq_session";
const focusId=new URLSearchParams(location.search).get("personnel");
let loadingWarnings=false;
const $=id=>document.getElementById(id);
function esc(value){const node=document.createElement("div");node.textContent=String(value??"");return node.innerHTML}
function toast(message){$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),3500)}
async function api(action,data={}){const token=localStorage.getItem(sessionKey);const res=await fetch(`${cfg.supabaseUrl}/functions/v1/${cfg.functionName}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":cfg.publishableKey,...(token?{"x-hq-session":token}:{})},body:JSON.stringify({action,...data})});const out=await res.json().catch(()=>({error:"Invalid server response."}));if(!res.ok)throw new Error(out.error||"Request failed.");return out}
function showBlocked(){$("warning-content").classList.add("hidden");$("warning-blocked").classList.remove("hidden");$("access-name").textContent="Guest Access";$("access-rank").textContent="View only";$("role-badge").textContent="HQ access required"}
function formatDate(value){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function targetName(item){const p=Array.isArray(item.personnel)?item.personnel[0]:item.personnel;return p?.name||"Unknown personnel"}
function renderWarnings(result){const access=result.access;$("access-name").textContent=access.name;$("access-rank").textContent=`${access.rank_code} · ${access.rank_name}`;$("role-badge").textContent=`${access.role==="owner"?"Owner HQ":"HQ Leadership"} · Protected`;const counts=new Map();for(const item of result.warnings){const name=targetName(item);const current=counts.get(item.personnel_id)||{name,count:0};current.count++;counts.set(item.personnel_id,current)}const summaries=[...counts.entries()].sort((a,b)=>b[1].count-a[1].count);$("warning-summary-list").innerHTML=summaries.length?summaries.map(([id,x])=>`<a class="warning-summary-card" href="warning.html?personnel=${encodeURIComponent(id)}"><strong>${esc(x.name)}</strong><span>${x.count} warning${x.count===1?"":"s"}</span></a>`).join(""):"";let shown=focusId?result.warnings.filter(x=>x.personnel_id===focusId):result.warnings;if(focusId){const focused=counts.get(focusId);$("warning-filter").innerHTML=`Showing ${esc(focused?.name||"selected personnel")} · <a href="warning.html">Show all warnings</a>`;$("warning-filter").classList.remove("hidden")}$("warning-list").innerHTML=shown.length?shown.map((item,index)=>`<article class="warning-entry"><div class="warning-entry-main"><div class="warning-entry-title"><strong>${esc(targetName(item))}</strong><span class="warning-number">Warning ${shown.length-index}</span></div><p class="log-meta">Issued by ${esc(item.actor_name)} · ${esc(formatDate(item.created_at))}</p><p class="log-reason">${esc(item.reason)}</p></div>${access.role==="owner"?`<button class="delete-warning" data-delete="${item.id}" type="button">Delete warning</button>`:""}</article>`).join(""):`<div class="empty">No warnings found.</div>`;document.querySelectorAll("[data-delete]").forEach(button=>button.onclick=()=>deleteWarning(Number(button.dataset.delete)))}
async function loadWarnings(){if(loadingWarnings)return;if(!localStorage.getItem(sessionKey)){showBlocked();return}loadingWarnings=true;try{renderWarnings(await api("warnings"))}catch(error){showBlocked();toast(error.message)}finally{loadingWarnings=false}}
async function deleteWarning(id){if(!confirm("Delete this warning permanently?"))return;try{await api("delete-warning",{id});toast("Warning deleted.");await loadWarnings()}catch(error){toast(error.message)}}
$("refresh-warnings").onclick=loadWarnings;
$("exit-warning").onclick=async()=>{try{if(localStorage.getItem(sessionKey))await api("logout")}catch{}localStorage.removeItem(sessionKey);location.href="index.html"};
loadWarnings();setInterval(()=>{if(!document.hidden)loadWarnings()},3000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)loadWarnings()});window.addEventListener("focus",loadWarnings);
